export default [
    {
        id: '0',
        image: 'https://content.r9cdn.net/himg/5f/24/17/ostrovok-9062672-cdb929d8deb777800f6f9cbc9adf4a20810d87ff-643296.jpg',
        type: 'Private Room',
        title: 'Bright room in the heart of the city',
        description: 'Lorem Ipsum is simplyLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        bed: 2,
        bedroom: 3,
        oldPrice: 25,
        newPrice: 20,
        totalPrice: 120,
        coordinate: {
            latitude: 28.3915637,
            longitude: -16.6291304,
        },
    },
    {
        id: '1',
        image: 'https://pavilionshotel.com/wp-content/uploads/sites/67/2018/03/8927633.jpg',
        type: 'Entire Flat',
        title: 'NEW lux. apartment in the center of Santa Cruz',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        bed: 3,
        bedroom: 2,
        oldPrice: 76,
        newPrice: 65,
        totalPrice: 390,
        coordinate: {
            latitude: 28.4815637,
            longitude: -16.2291304,
        },
    },
    {
        id: '2',
        image: 'https://q-xx.bstatic.com/xdata/images/hotel/840x460/311380761.jpg?k=46901c0dd2535a60b4d7609034fd160a119056dbf9ff5e64ea8788dfcb98d0fb&o=',
        type: 'Private Property',
        title: 'Green House Santa Cruz',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        bed: 2,
        bedroom: 1,
        oldPrice: 64,
        newPrice: 55,
        totalPrice: 330,
        coordinate: {
            latitude: 28.2515637,
            longitude: -16.3991304,
        },
    },
    {
        id: '3',
        image: 'https://www.etravelweek.com/sites/default/files/inline-images/xQuad,P20room.jpg.pagespeed.ic.wLqK56Ds1K.jpg',
        type: 'Entire Flat',
        title: 'Typical canarian house',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        bed: 4,
        bedroom: 3,
        oldPrice: 120,
        newPrice: 100,
        totalPrice: 600,
        coordinate: {
            latitude: 28.4815637,
            longitude: -16.2991304,
        },
    },
];
